name: Setup

description: Sets up workflow environment

inputs:
  npm_auth_token:
    description: 'Used to private install npm packages'
    required: true
  node_modules_cache_version:
    description: 'Controls node_modules cache version'
    default: v1
  storybook_root:
    description: 'Path to storybook'
    default: ./storybook

runs:
  using: "composite"

  steps:
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'

    - name: Use Library Cache
      uses: actions/cache@v2
      with:
        path: |
          ./node_modules/
          ~/.npm
        key: ${{ format('{0}-dialtone-vue-library-node-modules-{1}-{2}', runner.os, env.NODE_MODULES_CACHE_VERSION, hashFiles(format('package-lock.json'))) }}

    - name: Use Documentation Cache
      uses: actions/cache@v2
      with:
        path: |
          ${{ env.STORYBOOK_ROOT }}/node_modules/
        key: ${{ format('{0}-dialtone-vue-documentation-node-modules-{1}-{2}', runner.os, env.NODE_MODULES_CACHE_VERSION, hashFiles(format('{0}/package-lock.json', env.STORYBOOK_ROOT))) }}

    - name: Install dependencies
      run: npm ci
      env:
        NPM_AUTH_TOKEN: ${{ npm_auth_token }}
