module.exports = {
  version: 2,
  storybook: {
    exclude: [
      'Components/Badge: Default',
      'Components/Badge: Count',
      'Components/Badge: Examples',
      'Components/Breadcrumbs: Default',
      'Components/Breadcrumbs: Breadcrumb Item',
      'Components/Button: Default',
      'Components/Checkbox: Default',
      'Components/Checkbox Group: Default',
      'Components/Combobox: Empty',
      'Components/Datepicker',
      'Components/Dropdown',
      'Components/Emoji: Default',
      'Components/Emoji: Custom Emoji',
      'Components/Emoji Text Wrapper: Default',
      'Components/Icon: Default',
      'Components/Image Viewer: Default',
      'Components/Input Group',
      'Components/Item Layout',
      'Components/Keyboard Shortcut',
      'Components/Link',
      'Components/List Item',
      'Components/List Item Group',
      'Components/Modal',
      'Components/Notice',
      'Components/Pagination',
      'Components/Popover',
      'Components/Presence',
      'Components/Radio',
      'Components/Radio Group',
      'Components/Rich Text Editor',
      'Components/Root Layout',
      'Components/Select Menu',
      'Components/Skeleton',
      'Components/Stack',
      'Components/Tabs',
      'Components/Toast',
      'Components/Toggle',
      'Components/Tooltip',
      'Components/Validation Messages',
      'Recipes/',
      'Utilities/',
      'Visual Testing/',
    ],
  },
  snapshot: {
    enableJavaScript: true,
    widths: [1280],
  },
  discovery: {
    disableCache: true,
    networkIdleTimeout: 150,
  },
};
