name: Bundle size regression checker

on:
  pull_request:
    branches: [ staging, staging-vue3, vue3, production ]
  push:
    branches: [ staging, staging-vue3 ]

jobs:
  base_bundle_size:
    runs-on: ubuntu-latest

    outputs:
      size: ${{ steps.base_bundle_size.outputs.size }}

    steps:
      - name: Check out branch
        uses: actions/checkout@v2
        with:
          ref: ${{ github.base_ref }}

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm ci

      - name: Get bundle size
        id: base_bundle_size
        run: npm run build && echo "::set-output name=size::$(gzip -c dist/*.js | wc -c)"

  pr_bundle_size:
    runs-on: ubuntu-latest

    outputs:
      size: ${{ steps.pr_bundle_size.outputs.size }}

    steps:
      - name: Check out branch
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm ci

      - name: Get bundle size
        id: pr_bundle_size
        run: npm run build && echo "::set-output name=SIZE::$(gzip -c dist/*.js | wc -c)"

  check_regression:
    runs-on: ubuntu-latest

    needs: [base_bundle_size, pr_bundle_size]
    steps:
      - run: echo ${{needs.base_bundle_size.outputs.size}} ${{needs.pr_bundle_size.outputs.size}}
