name: Deploy

on:
  push:
    branches:
      - setup-github-pages

jobs:
  deploy:
    concurrency: deploy-ci-${{ github.ref }}
    runs-on: ubuntu-latest

    env:
      NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

    steps:
      - name: Check out branch
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: parse branch from ref
        id: branch
        run: echo ::set-output name=BRANCH::${GITHUB_REF/refs\/heads\//}

      - name: Set npm token
        run: npm config set //registry.npmjs.org/:_authToken=${{ secrets.NPM_AUTH_TOKEN }}

      - name: Install dependencies
        run: npm ci

      - name: Run unit tests
        run: npm run test

      - name: Run Linters
        run: npm run lint

      - name: Build storybook
        run: npm run storybook:install && npm run storybook:build

      - name: Deploy production
        if: ${{ github.ref == 'refs/heads/production' }}
        run: npm publish

      - name: Deploy to GitHub Pages
        if: ${{ github.ref == 'refs/heads/setup-github-pages' }}
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          branch: gh-pages
          folder: storybook/compiled

      - name: Deploy prerelease
        if: ${{ github.ref != 'refs/heads/production' }}
        run: npm publish --tag ${{ steps.branch.outputs.BRANCH }}

      - name: Github Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release --extends ./release-ci.config.js
