name: Linters

on:
  pull_request:
    branches: [ main, release ]
  push:
    branches: [ main ]

jobs:
  linters:

    runs-on: ubuntu-latest

    env:
      NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
      STORYBOOK_ROOT: ./storybook
      NODE_MODULES_CACHE_VERSION: v1

    steps:
      - name: Check out branch
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: Use Cache
        uses: actions/cache@v2
        with:
          path: |
            ./node_modules/
            ${{ env.STORYBOOK_ROOT }}/node_modules/
            ~/.npm
          key: ${{ format('{0}-dialtone-vue-node-modules-{1}-{2}-{3}', runner.os, env.NODE_MODULES_CACHE_VERSION, hashFiles(format('package-lock.json')), hashFiles(format('{0}/package-lock.json', env.STORYBOOK_ROOT))) }}

      - name: Install dependencies
        run: npm ci

      - name: Run code linters
        run: npm run lint:code

      - name: Run docs linters
        run: npm run lint:docs
