name: Linters

on:
  pull_request:
    branches: [ main, release ]
  push:
    branches: [ main ]

jobs:
  linters:

    runs-on: ubuntu-latest

    env:
      NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

    steps:
      - name: Check out branch
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: Install Vue CLI
        run: npm install -g @vue/cli

      - name: Install dependencies
        run: npm ci

      - name: Run code linters
        run: npm run lint:code

      - name: Run docs linters
        run: npm run lint:docs
