name: Unit Tests

on:
  pull_request:
    branches: [ main, release ]
  push:
    branches: [ main ]

jobs:
  unit_tests:

    runs-on: ubuntu-latest

    steps:
      - name: Setup
        uses: actions/setup@v1

      - name: Run unit tests
        run: npm run test
