name: Unit Tests

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  run_unit_tests:

    runs-on: ubuntu-latest

    steps:
      - name: Check out branch
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: Install dependencies
        run: npm install -g @vue/cli
        run: npm install

      - name: Run unit tests
        run: npm run test

      env:
        NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
