name: Unit Tests

on:
  pull_request:
    branches: [ main, release ]
  push:
    branches: [ main ]

jobs:
  unit_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Check out branch
        uses: actions/checkout@v2

      - name: Setup
        uses: ./.github/actions/setup

      - name: Run unit tests
        run: npm run test
