name: Visual Tests
on:
  pull_request:
    branches:
      - staging
      - staging-vue3
  push:
    branches:
      - staging
      - staging-vue3
jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

    steps:
      - name: Check out branch
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16'

      - name: Set npm token
        run: npm config set //registry.npmjs.org/:_authToken=${{ secrets.NPM_AUTH_TOKEN }}

      - name: Install dependencies
        run: npm ci

      - name: Install storybook dependencies
        run: npm run storybook:install

      - name: Build storybook
        run: npm run storybook:build

      - name: Visual Tests
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
        run: npx percy storybook --verbose storybook/compiled
